name: myexpanses
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  path_provider: any
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any
  #flutter_lints: ^1.0.0

  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: true
  ios: true
  image_path: "Assets/images/1.jpeg"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - Assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Rockwell
      fonts:
        - asset: Assets/fonts/ROCC____.TTF
        - asset: Assets/fonts/ROCCB___.TTF
        - asset: Assets/fonts/ROCK.TTF
        - asset: Assets/fonts/ROCKB.TTF
        - asset: Assets/fonts/ROCKBI.TTF
        - asset: Assets/fonts/ROCKEB.TTF
        - asset: Assets/fonts/ROCKI.TTF

    - family: MyFont
      fonts:
        - asset: Assets/fonts/myFont1.ttf
        - asset: Assets/fonts/FtySpeedyCasualNcv-lzEw.ttf
